name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0-209.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  intl: ^0.19.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/hearts_pattern.png
    - assets/logo.png
    - assets/Rectangle.png
    - assets/logo_small.png
    - assets/couple_avatar.png
    - assets/heart_empty_pixel.png
    - assets/heart_full_pixel.png
    - assets/piquenique.jpg
    - assets/cinema_casa.jpg
    - assets/culinaria.jpg
    - assets/cidade_nova.jpg
    - assets/jogos.jpg
    - assets/logo_cor.png

  # A seção 'fonts:' deve estar COMPLETAMENTE COMENTADA ou REMOVIDA se não for usada.
  # Se você a descomentou, o erro "Mapping values are not allowed here"
  # foi causado por um pequeno erro de indentação ou um hífen extra que eu corrigi
  # na minha sugestão de código (mas que pode ter sido copiado errado).
  # A maneira mais segura é garantir que ela esteja assim (comentada ou ausente):
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700